### ISSUE TITLE
Export rust QCS ClientConfiguration to python

### ISSUE THREAD

**Issue by jselig-rigetti** [rigetti/qcs-sdk-rust#231]
From https://github.com/rigetti/qcs-sdk-rust/pull/230/files#r1068297511

As a `pyquil` user, I want to be able to provide a custom QCS client configuration when making API calls.

Since [`qcs-api-client`](https://pypi.org/project/qcs-api-client/) is being removed from pyquil as part of https://github.com/rigetti/pyquil/issues/1485, we'll need to replace the python [`QCSClientConfiguration`](https://github.com/rigetti/qcs-api-client-python/blob/main/qcs_api_client/client/_configuration/configuration.py#L25) functionality with the rust [`ClientConfiguration`](https://docs.rs/qcs-api-client-common/latest/qcs_api_client_common/configuration/struct.ClientConfiguration.html).

So far in [qcs-sdk-rust/pull/230](https://github.com/rigetti/qcs-sdk-rust/pull/230/files#r1068297511) there is only support for the environmentally-bootstrapped configuration.

---

<details>
<summary>previous suggestion, no longer relevant</summary>

Since `QCSClientConfiguration` is an object with getters, I'm thinking the solution looks like:
- Convert the object into a `dict`
- Pass it to rust as a `PyDict`
- Construct [`ClientConfiguration`](https://github.com/rigetti/qcs-api-client-rust/blob/main/qcs-api-client-common/src/configuration/mod.rs#L73) as closely as possible (likely requires changes to the crate)

</details>

**Comment by kalzoo** [comment]
Replied [on the comment](https://github.com/rigetti/qcs-sdk-rust/pull/230/files#r1068728184) as well, but it seems to me that of the two, we should take the Rust ClientConfiguration as authoritative rather than serializing the Python QCSClientConfiguration.

By that, I mean that we should _not_ serialize the Python QCSClientConfiguration to a dict and then figure out what to do with that dict at the FFI boundary. We should instead accept a Rust ClientConfiguration and then expose methods on that for a Python user to call. This will be consistent with the general pattern in the Python bindings.
